dataset_path: /home/kit/iti/zn2950/ws/workspaces/llm_extraction_workspace/datasets/synthesis_paragraphs
csv_path: /home/kit/iti/zn2950/ws/src/scripts/tobias/SynMOF_M_out.csv
#checkpoint_path: /pfs/work7/workspace/scratch/lz5921-chkpt/
models:
- model_name: LLaMa 3.1 8B
  model_path: /home/kit/iti/zn2950/ws/workspaces/llm_extraction_workspace/code/Llama-3.1-8B
  model_type: text-generation
- model_name: LLaMa 3.1 8B Instruct
  model_path: /home/kit/iti/zn2950/ws/workspaces/llm_extraction_workspace/code/Llama-3.1-8B-Instruct
  model_type: text-generation

extract_config:
  additive:
    type: string
    convert_funcs:
    - ans2cid
    dataset_cols:
    - additive1
  solvent:
    type: string
    convert_funcs:
    - ans2cid
    dataset_cols:
    - solvent1
  temperature:
    type: number
    unit: C
    convert_funcs:
    - ans2temperature
    dataset_cols:
    - temperature_Celsius
  time:
    type: number
    unit: h
    convert_funcs:
    - ans2time
    dataset_cols:
    - time_h
