dataset_path: /home/kit/iti/lz5921/mof_synthesis/synthesis_paragraphs
checkpoint_path: /pfs/work7/workspace/scratch/lz5921-chkpt/
models:
- model_name: LLaMa 13B
  model_path: /pfs/work8/workspace/ffuc/scratch/lz5921-llms/llama.cpp/models/13B/
  model_type: text-generation
- model_name: LLaMa 2 13B
  model_path: /pfs/work7/workspace/scratch/lz5921-llama/Llama-2-13b/
  model_type: text-generation
- model_name: Vicuna 13B
  model_path: /pfs/work8/workspace/ffuc/scratch/lz5921-llms/vicuna-13b-1.1/
  model_type: text-generation
extract_config:
  additive:
    type: string
    convert_funcs:
    - ans2cid
    dataset_cols:
    - additive1
  solvent:
    type: string
    convert_funcs:
    - ans2cid
    dataset_cols:
    - solvent1
  temperature:
    type: number
    unit: C
    convert_funcs:
    - ans2temperature
    dataset_cols:
    - temperature_Celsius
  time:
    type: number
    unit: h
    convert_funcs:
    - ans2time
    dataset_cols:
    - time_h
