#!/bin/bash
#SBATCH --job-name=prompt_1
#SBATCH --output=results/prompt_1_%j.out
#SBATCH --error=results/prompt_1_%j.err
#SBATCH --partition=gpu_4_a100
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --time=120:00
#SBATCH --nodes=1
#SBATCH --mail-type=NONE
#SBATCH --constraint=LSDF

source ~/.bashrc
module load devel/cuda/11.8
module load devel/miniconda/23.9.0-py3.9.15
conda info --envs
conda activate llm-extraction

echo "run_7b"
echo "GPU:1"
echo
echo "NVDIA-SMI OUTPUT"
nvidia-smi

cd /home/kit/iti/zn2950/ws/src/master_thesis/legacy_code

poetry run main evaluate --settings settings/settings_llama_31.yml --only-model "LLaMa 3.1 8B Instruct" --stats-path stats_prompt_1.yml --prompt "Extract MOF synthesis conditions from the text. Use these rules: - Temperature: Highest reaction temperature (25°C if unspecified) - Time: Longest duration maintained at highest temperature - Solvent: Choose one main solvent (no mixtures or ratios) - Additive: Choose one additive, or write 'None' if absent"
