#!/bin/bash
#SBATCH --job-name=prompt_2
#SBATCH --output=results/prompt_2_%j.out
#SBATCH --error=results/prompt_2_%j.err
#SBATCH --partition=gpu_4_a100
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --time=90:00
#SBATCH --nodes=1
#SBATCH --mail-type=NONE
#SBATCH --constraint=LSDF

source ~/.bashrc
module load devel/cuda/11.8
module load devel/miniconda/23.9.0-py3.9.15
conda info --envs
conda activate llm-extraction

echo "run_7b"
echo "GPU:1"
echo
echo "NVDIA-SMI OUTPUT"
nvidia-smi

cd /home/kit/iti/zn2950/ws/src/master_thesis/legacy_code

poetry run main evaluate --settings settings/settings_llama_31.yml --only-model "LLaMa 3.1 8B Instruct" --stats-path stats_prompt_1.yml --prompt "Extract synthesis conditions from the text in the following format: temperature (highest reaction temp, use 25°C if not specified), time (longest duration at highest temp), one solvent (if multiple present, choose one), and one additive (write 'None' if no additive present)."