#!/bin/bash
#SBATCH --job-name=haicore_prompt_1
#SBATCH --output=results/haicore_prompt_1_%j.out
#SBATCH --error=results/haicore_prompt_1_%j.err
#SBATCH --partition=normal
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:full:1
#SBATCH --time=90:00
#SBATCH --nodes=1
#SBATCH --mail-type=NONE
#SBATCH --constraint=LSDF

source ~/.bashrc
module load devel/cuda/11.8
conda info --envs
conda activate llm-extraction

echo "run llama 3.1 8B Instruct, prompt 1"
echo "GPU:1"
echo
echo "NVDIA-SMI OUTPUT"
nvidia-smi

cd /gfse/data/LSDF/lsdf01/lsdf/kit/iti/zn2950/ws/master_thesis/legacy_code

poetry run main evaluate --settings settings/settings_llama_31.yml --only-model "LLaMa 3.1 8B Instruct" --stats-path stats_haicore_prompt_1.yml --prompt "Extract MOF synthesis conditions from the text. Use these rules: - Temperature: Highest reaction temperature (25°C if unspecified) - Time: Longest duration maintained at highest temperature - Solvent: Choose one main solvent (no mixtures or ratios) - Additive: Choose one additive, or write 'None' if absent"
