#!/bin/bash
#SBATCH --job-name=run_large
#SBATCH --output=results/run_large_%j.out
#SBATCH --error=results/run_large_%j.err
#SBATCH --partition=dev_gpu_4_a100
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --time=30:00
#SBATCH --nodes=1
#SBATCH --mail-type=NONE

cd $SLURM_SUBMIT_DIR

source ~/.bashrc
module load devel/cuda

echo "run_large"
echo "GPU:1"
echo
echo "NVDIA-SMI OUTPUT"
nvidia-smi

cd ~/llms/mthesis/code

# poetry run main train --stats stats_7b.yml --settings settings/settings_7b.yml
# poetry run main train --settings settings/settings_7b.yml
poetry run main evaluate --stats-path stats_large.yml --settings settings/settings_large.yml --only-model="Vicuna 33B"
